### ISSUE TITLE
Contact(s) Creation

### ISSUE THREAD

**Issue by fashyl** [spytech-arkx/mern-crm#12]
### 🎯 **Objective** 
  - Design database schema for storing contact information including fields such as name, email, phone number, and preferences.
  - Create RESTful API endpoints for creating new contacts.

### **Guidelines**
  - Endpoint: POST /api/contacts
  - Request Body: { name, email, phoneNumber, _preferences_... }

### Tasklist
- [x] Design
- [x] Implementation
- [x] Error and Response Handling
- [x] ✔ Works!

**Comment by depliant** [comment]
Tasklist
- [ ] Design
- [ ] Implementation
- [ ] Error and Response Handling
- [ ] ✔ Works!
