### ISSUE TITLE
Deal Creation

### ISSUE THREAD

**Issue by fashyl** [spytech-arkx/mern-crm#27]
### 🎯 **Objective** 
  - Design database schema for storing deal information including fields such as deal name, description, amount, stage, and associated contacts/companies.
  - Create RESTful API endpoints for creating new deals.
### **Guidelines**
- Endpoint: POST /api/deals
- Request Body: { name, description, amount, stage, associated contacts, products or services being offered, expected close date, companies, and any relevant notes or attachments. }
> stage : prospecting, qualification, proposal, negotiation, and closure.  -->
### Tasklist
- [x] Design
- [x] Route
- [x] Controller
- [x] API Model 
- [x] Error and Response Handling
- [x] ✔ Works!

**Comment by ZakErGithub** [comment]
Tasklist

- [ ]     Design
- [ ]     Route
- [ ]     Controller
- [ ]     API Model
- [ ]     Error and Response Handling
- [ ]     ✔ Works!

**Comment by ZakErGithub** [comment]
- [x]     Design
- [x]     Route
- [x]     Controller
- [ ]     API Model
- [ ]     Error and Response Handling
- [ ]     ✔ Works!
