### ISSUE TITLE
Deal Retrieval

### ISSUE THREAD

**Issue by fashyl** [spytech-arkx/mern-crm#28]
### 🎯 **Objective** 
  - Develop API endpoints for retrieving a deal or all the deals
  - Sprint 2 :  Retrieve deal information based on user query criteria.
  - Sprint 2: Implement pagination and search functionality for efficient deal management.
### **Guidelines**
 - Endpoint: GET /api/deals
 - Endpoint: GET /api/deals/:id
### Tasklist
- [x] Route
- [x] Controller
- [x] API Model 
- [ ] Error and Response Handling
- [x] ✔ Works!

**Comment by ZakErGithub** [comment]
Tasklist

- [x]     Route
- [x]     Controller
- [x]     API Model
- [x]     Error and Response Handling
- [x]     ✔ Works!
