### ISSUE TITLE
Deal Update

### ISSUE THREAD

**Issue by fashyl** [spytech-arkx/mern-crm#29]
### 🎯 **Objective** 
  - Enable users to update existing deal information, including deal name, description, amount, stage, and associated contacts/companies.
  - Implement validation and error handling for deal form submissions.
### **Guidelines**
  - Endpoint: PUT /api/deals/:id
  - Request Body: { name, description, amount, stage, contacts, companies...}
### Tasklist
- [x] Route
- [x] Controllers
- [x] API Model 
- [ ] Error and Response Handling
- [ ] Data validation
- [x] ✔ Works!

**Comment by ZakErGithub** [comment]
Tasklist
- [x]  Route
- [x] Controllers
- [x] API Model
- [x] Error and Response Handling
- [x] Data validation
- [x] ✔ Works!
